Add Docker and SELinux tests
stackhpc/stackhpc-cloud-tests pull request #4
Opened 2024-05-17 08:29 UTC by markgoddard

- Add initial Docker tests
- Add SELinux test

2025-03-31 13:48 UTC, Alex-Welsh requested changes

2025-03-31 13:48 UTC, Alex-Welsh commented on stackhpc_cloud_tests/host/test_selinux.py
> +    selinux = [" ".join(x.split()) for x in selinux]
Can we avoid the use of `expected_state` here and just use `expected_mode`?
```suggestion
def test_selinux(host):
    """Check that SELinux is enabled and permissive on supported systems."""
    # Adapted from Kayobe host configure tests:
    # https://opendev.org/openstack/kayobe/src/branch/master/playbooks/kayobe-overcloud-host-configure-base/tests/test_overcloud_host_configure.py
    if host.system_info.distribution in {"debian", "ubuntu"}:
        pytest.skip(reason="SELinux is not supported on Debian or Ubuntu")
    # Desired state: enforcing, permissive or disabled
    expected_mode = os.environ["SELINUX_STATE"]
    assert expected_mode in {"enforcing", "permissive", "disabled"}
    expected_status = "disabled" if expected_mode == "disabled" else "enabled"
    selinux = host.check_output("sestatus")
    selinux = selinux.splitlines()
    # Remove duplicate whitespace characters in output
    selinux = [" ".join(x.split()) for x in selinux]
```

2025-03-31 13:48 UTC, Alex-Welsh commented on stackhpc_cloud_tests/host/test_selinux.py
> +    # https://opendev.org/openstack/kayobe/src/branch/master/playbooks/kayobe-overcloud-host-configure-base/tests/test_overcloud_host_configure.py
nit: would be best to use a permalink to a specific commit here. Referring to master might break the link later down the line

2025-03-31 13:48 UTC, Alex-Welsh commented on stackhpc_cloud_tests/host/test_selinux.py
> +        assert f"Mode from config file: {expected_mode}" in selinux
I'm surprised this works, since the whitespace looks like it varies, though it's probably fine if it's used upstream.

Example output from `sestatus`:
```
Loaded policy name:             targeted
Current mode:                   permissive
```

2025-04-02 10:10 UTC, maxstack commented on stackhpc_cloud_tests/host/test_selinux.py
> +    # https://opendev.org/openstack/kayobe/src/branch/master/playbooks/kayobe-overcloud-host-configure-base/tests/test_overcloud_host_configure.py
Absolutely, linked to the commit and the test function.

2025-04-02 11:56 UTC, Alex-Welsh approved these changes

2025-04-02 11:56 UTC, merged